<?php

namespace App\Providers\Filament;

use App\Http\Middleware\AuthenticateFilament;
use App\Models\Setting;
use Filament\Http\Middleware\DisableBladeIconComponents;
use Filament\Http\Middleware\DispatchServingFilamentEvent;
use Filament\Navigation\MenuItem;
use Filament\Navigation\NavigationGroup;
use Filament\Pages;
use Filament\Panel;
use Filament\PanelProvider;
use Filament\Support\Colors\Color;
use Filament\View\PanelsRenderHook;
use Filament\Widgets;
use Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse;
use Illuminate\Cookie\Middleware\EncryptCookies;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;
use Illuminate\Routing\Middleware\SubstituteBindings;
use Illuminate\Session\Middleware\AuthenticateSession;
use Illuminate\Session\Middleware\StartSession;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\Middleware\ShareErrorsFromSession;

class AdminPanelProvider extends PanelProvider
{
    /**
     * Build the plugin list, gracefully skipping any plugin whose
     * composer package hasn't been installed yet.
     *
     * @return array<int, \Filament\Contracts\Plugin>
     */
    protected static function buildPlugins(): array
    {
        $plugins = [];

        // ApexCharts widgets (analytics page)
        if (class_exists(\Leandrocfe\FilamentApexCharts\FilamentApexChartsPlugin::class)) {
            $plugins[] = \Leandrocfe\FilamentApexCharts\FilamentApexChartsPlugin::make();
        }

        // Ctrl+K command palette (replaces built-in global search UI when installed)
        if (class_exists(\pxlrbt\FilamentSpotlight\SpotlightPlugin::class)) {
            $plugins[] = \pxlrbt\FilamentSpotlight\SpotlightPlugin::make();
        }

        // Granular RBAC (policies generated by `php artisan shield:generate --all`)
        if (class_exists(\BezhanSalleh\FilamentShield\FilamentShieldPlugin::class)) {
            $plugins[] = \BezhanSalleh\FilamentShield\FilamentShieldPlugin::make();
        }

        // FullCalendar (plugin form; the package ships as a widget, no plugin class needed)
        // No ->plugins() registration required for saade/filament-fullcalendar.

        // Tiptap rich-text editor (no plugin class needed; used via field in PageResource)

        // Spatie activity-log UI (replaces custom ActivityLogResource)
        if (class_exists(\Rmsramos\Activitylog\ActivitylogPlugin::class)) {
            $plugins[] = \Rmsramos\Activitylog\ActivitylogPlugin::make()
                ->navigationGroup('Tools')
                ->navigationIcon('heroicon-o-document-text')
                ->navigationSort(98)
                ->label('Log')
                ->pluralLabel('Logs');
        }

        // Queue / failed-job monitor (replaces custom FailedJobs page)
        if (class_exists(\Croustibat\FilamentJobsMonitor\FilamentJobsMonitorPlugin::class)) {
            $plugins[] = \Croustibat\FilamentJobsMonitor\FilamentJobsMonitorPlugin::make();
        }

        // Global "+" quick-create in topbar for all resources
        if (class_exists(\Awcodes\FilamentQuickCreate\QuickCreatePlugin::class)) {
            $plugins[] = \Awcodes\FilamentQuickCreate\QuickCreatePlugin::make()
                ->sortBy('label')
                ->excludes([
                    \Croustibat\FilamentJobsMonitor\Resources\QueueMonitorResource::class,
                    \Rmsramos\Activitylog\Resources\ActivitylogResource::class,
                ]);
        }

        // User-resizable table columns (persisted per user)
        if (class_exists(\Asmit\ResizedColumn\ResizedColumnPlugin::class)) {
            $plugins[] = \Asmit\ResizedColumn\ResizedColumnPlugin::make();
        }

        // Overlook — resource overview widget (used via Dashboard widget list)
        if (class_exists(\Awcodes\Overlook\OverlookPlugin::class)) {
            $plugins[] = \Awcodes\Overlook\OverlookPlugin::make()
                ->alphabetical()
                ->excludes([
                    \Croustibat\FilamentJobsMonitor\Resources\QueueMonitorResource::class,
                    \Rmsramos\Activitylog\Resources\ActivitylogResource::class,
                ]);
        }

        return $plugins;
    }

    protected static function buildNavigationGroups(): array
    {
        $groups = [
            ['key' => 'Overview',         'collapsed' => false, 'icon' => 'heroicon-o-squares-2x2'],
            ['key' => 'Content',          'collapsed' => false, 'icon' => 'heroicon-o-video-camera'],
            ['key' => 'Users & Messages', 'collapsed' => false, 'icon' => 'heroicon-o-users'],
            ['key' => 'Monetization',     'collapsed' => false, 'icon' => 'heroicon-o-banknotes'],
            ['key' => 'Appearance',       'collapsed' => false, 'icon' => 'heroicon-o-paint-brush'],
            ['key' => 'Integrations',     'collapsed' => true,  'icon' => 'heroicon-o-puzzle-piece'],
            ['key' => 'System',           'collapsed' => true,  'icon' => 'heroicon-o-cog-6-tooth'],
            ['key' => 'Tools',            'collapsed' => true,  'icon' => 'heroicon-o-wrench-screwdriver'],
        ];

        return array_map(function (array $g) {
            $group = NavigationGroup::make($g['key']);
            if ($g['collapsed']) {
                $group->collapsed();
            }
            if (!empty($g['icon'])) {
                $group->icon($g['icon']);
            }
            return $group;
        }, $groups);
    }

    public function panel(Panel $panel): Panel
    {
        // Resolve site logo for admin panel branding
        $brandLogo = null;
        $brandName = 'HubTube';
        try {
            $siteLogo = Setting::get('site_logo', '');
            if ($siteLogo) {
                // Use same URL resolution as frontend: /storage/ prefix for relative paths
                if (str_starts_with($siteLogo, 'http://') || str_starts_with($siteLogo, 'https://') || str_starts_with($siteLogo, '/')) {
                    $brandLogo = $siteLogo;
                } else {
                    $brandLogo = '/storage/' . $siteLogo;
                }
            }
            $brandName = Setting::get('site_title', 'HubTube') ?: 'HubTube';
        } catch (\Throwable $e) {
            // Database may not be available during boot
        }

        // Resolve favicon for admin panel
        $faviconUrl = null;
        try {
            $siteFavicon = Setting::get('site_favicon', '');
            if ($siteFavicon) {
                if (str_starts_with($siteFavicon, 'http://') || str_starts_with($siteFavicon, 'https://') || str_starts_with($siteFavicon, '/')) {
                    $faviconUrl = $siteFavicon;
                } else {
                    $faviconUrl = '/storage/' . $siteFavicon;
                }
            }
        } catch (\Throwable $e) {
            // Database may not be available during boot
        }

        $builder = $panel
            ->default()
            ->id('admin')
            ->path('admin')
            ->darkMode(true, true)
            ->brandName($brandName)
            ->font('Inter')
            ->colors([
                'primary' => Color::Indigo,
                'danger'  => Color::Rose,
                'warning' => Color::Amber,
                'success' => Color::Emerald,
                'info'    => Color::Sky,
                'gray'    => Color::Zinc,
            ])
            ->globalSearchKeyBindings(['command+k', 'ctrl+k'])
            ->globalSearchFieldKeyBindingSuffix();

        if ($faviconUrl) {
            $builder = $builder->favicon($faviconUrl);
        }

        if ($brandLogo) {
            $builder = $builder
                ->brandLogo($brandLogo)
                ->brandLogoHeight('2rem');
        }

        return $builder
            ->login()
            ->profile()
            ->userMenuItems([
                MenuItem::make()
                    ->label('View Site')
                    ->url('/')
                    ->icon('heroicon-o-globe-alt'),
                MenuItem::make()
                    ->label('Flush Cache')
                    ->icon('heroicon-o-arrow-path')
                    ->url('/admin/flush-cache')
                    ->color('warning'),
            ])
            ->discoverResources(in: app_path('Filament/Resources'), for: 'App\\Filament\\Resources')
            ->discoverPages(in: app_path('Filament/Pages'), for: 'App\\Filament\\Pages')
            ->pages([
                \App\Filament\Pages\Dashboard::class,
            ])
            ->discoverWidgets(in: app_path('Filament/Widgets'), for: 'App\\Filament\\Widgets')
            ->widgets([])
            ->renderHook(
                PanelsRenderHook::TOPBAR_START,
                function (): string {
                    try {
                        return view('filament.widgets.system-status-bar', [
                            'metrics' => app(\App\Services\SystemStatusBar::class)->getMetrics(),
                        ])->render();
                    } catch (\Throwable $e) {
                        return '';
                    }
                },
            )
            ->renderHook(
                PanelsRenderHook::HEAD_END,
                fn (): string => '<style>' . file_get_contents(resource_path('css/filament/admin/theme.css')) . '</style>',
            )
            ->navigationGroups(static::buildNavigationGroups())
            ->plugins(static::buildPlugins())
            // Collapsed sidebar becomes a slim icon rail (not fully hidden),
            // shifting page content left so widgets gain horizontal space.
            ->sidebarCollapsibleOnDesktop()
            ->spa()
            ->middleware([
                EncryptCookies::class,
                AddQueuedCookiesToResponse::class,
                StartSession::class,
                AuthenticateSession::class,
                ShareErrorsFromSession::class,
                VerifyCsrfToken::class,
                SubstituteBindings::class,
                DisableBladeIconComponents::class,
                DispatchServingFilamentEvent::class,
            ])
            ->authMiddleware([
                AuthenticateFilament::class,
            ])
            ->authGuard('web');
    }
}
