<?php

namespace App\Providers\Filament;

use Leandrocfe\FilamentApexCharts\FilamentApexChartsPlugin;
use BezhanSalleh\FilamentShield\FilamentShieldPlugin;
use Croustibat\FilamentJobsMonitor\FilamentJobsMonitorPlugin;
use Awcodes\Overlook\OverlookPlugin;
use Croustibat\FilamentJobsMonitor\Resources\QueueMonitorResource;
use Throwable;
use App\Filament\Pages\Dashboard;
use App\Services\SystemStatusBar;
use Filament\Contracts\Plugin;
use App\Http\Middleware\AuthenticateFilament;
use App\Models\Setting;
use Filament\Http\Middleware\DisableBladeIconComponents;
use Filament\Http\Middleware\DispatchServingFilamentEvent;
use Filament\Navigation\MenuItem;
use Filament\Navigation\NavigationGroup;
use Filament\Pages;
use Filament\Panel;
use Filament\PanelProvider;
use Filament\Support\Colors\Color;
use Openplain\FilamentShadcnTheme\Color as ShadcnColor;
use Filament\View\PanelsRenderHook;
use Filament\Widgets;
use Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse;
use Illuminate\Cookie\Middleware\EncryptCookies;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;
use Illuminate\Routing\Middleware\SubstituteBindings;
use Illuminate\Session\Middleware\AuthenticateSession;
use Illuminate\Session\Middleware\StartSession;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\Middleware\ShareErrorsFromSession;
use Filafly\Icons\Phosphor\PhosphorIcons;
use Muazzam\SlickScrollbar\SlickScrollbarPlugin;


class AdminPanelProvider extends PanelProvider
{
    /**
     * Build the plugin list, gracefully skipping any plugin whose
     * composer package hasn't been installed yet.
     *
     * @return array<int, Plugin>
     */
    protected static function buildPlugins(): array
    {
        $plugins = [];

        // ApexCharts widgets (analytics page)
        if (class_exists(FilamentApexChartsPlugin::class)) {
            $plugins[] = FilamentApexChartsPlugin::make();
        }

        // Granular RBAC (policies generated by `php artisan shield:generate --all`)
        if (class_exists(FilamentShieldPlugin::class)) {
            $plugins[] = FilamentShieldPlugin::make();
        }

        // Queue / failed-job monitor (replaces custom FailedJobs page)
        if (class_exists(FilamentJobsMonitorPlugin::class)) {
            $plugins[] = FilamentJobsMonitorPlugin::make();
        }

        // Overlook — resource overview widget (used via Dashboard widget list)
        if (class_exists(OverlookPlugin::class)) {
            $plugins[] = OverlookPlugin::make()
                ->alphabetical()
                ->excludes([
                    QueueMonitorResource::class,
                ]);
        }

        if (class_exists(SlickScrollbarPlugin::class)) {
            $plugins[] = SlickScrollbarPlugin::make()
                ->size('6px')
                ->color('#ef4444')
                ->hoverColor('rgb(220 38 38)');
        }

        $plugins[] = PhosphorIcons::make()->regular();

        return $plugins;
    }

    protected static function buildNavigationGroups(): array
    {
        $groups = [
            ['key' => 'Overview',         'collapsed' => false, 'icon' => 'phosphor-squares-four'],
            ['key' => 'Content',          'collapsed' => false, 'icon' => 'phosphor-video-camera'],
            ['key' => 'Users & Messages', 'collapsed' => false, 'icon' => 'phosphor-users'],
            ['key' => 'Monetization',     'collapsed' => false, 'icon' => 'phosphor-currency-dollar'],
            ['key' => 'Appearance',       'collapsed' => false, 'icon' => 'phosphor-paint-brush'],
            ['key' => 'Integrations',     'collapsed' => true,  'icon' => 'phosphor-puzzle-piece'],
            ['key' => 'System',           'collapsed' => true,  'icon' => 'phosphor-gear'],
            ['key' => 'Tools',            'collapsed' => true,  'icon' => 'phosphor-wrench'],
        ];

        return array_map(function (array $g) {
            $group = NavigationGroup::make($g['key']);
            if ($g['collapsed']) {
                $group->collapsed();
            }
            if (!empty($g['icon'])) {
                $group->icon($g['icon']);
            }
            return $group;
        }, $groups);
    }

    public function panel(Panel $panel): Panel
    {
        // Resolve site logo for admin panel branding
        $brandLogo = null;
        $brandName = 'HubTube';
        try {
            $siteLogo = Setting::get('site_logo', '');
            if ($siteLogo) {
                // Use same URL resolution as frontend: /storage/ prefix for relative paths
                if (str_starts_with($siteLogo, 'http://') || str_starts_with($siteLogo, 'https://') || str_starts_with($siteLogo, '/')) {
                    $brandLogo = $siteLogo;
                } else {
                    $brandLogo = '/storage/' . $siteLogo;
                }
            }
            $brandName = Setting::get('site_title', 'HubTube') ?: 'HubTube';
        } catch (Throwable $e) {
            // Database may not be available during boot
        }

        // Resolve favicon for admin panel
        $faviconUrl = null;
        try {
            $siteFavicon = Setting::get('site_favicon', '');
            if ($siteFavicon) {
                if (str_starts_with($siteFavicon, 'http://') || str_starts_with($siteFavicon, 'https://') || str_starts_with($siteFavicon, '/')) {
                    $faviconUrl = $siteFavicon;
                } else {
                    $faviconUrl = '/storage/' . $siteFavicon;
                }
            }
        } catch (Throwable $e) {
            // Database may not be available during boot
        }

        $builder = $panel
            ->default()
            ->id('admin')
            ->path('admin')
            ->darkMode(true, true)
            ->brandName($brandName)
            ->font('Inter')
            ->colors([
                'primary' => ShadcnColor::Default,
                'danger'  => ShadcnColor::Red,
                'warning' => ShadcnColor::Yellow,
                'success' => ShadcnColor::Green,
                'info'    => ShadcnColor::Blue,
                'gray'    => ShadcnColor::Default,
            ]);

        if ($faviconUrl) {
            $builder = $builder->favicon($faviconUrl);
        }

        if ($brandLogo) {
            $builder = $builder
                ->brandLogo($brandLogo)
                ->brandLogoHeight('2rem');
        }

        return $builder
            ->login()
            ->profile()
            ->userMenuItems([
                MenuItem::make()
                    ->label('View Site')
                    ->url('/')
                    ->icon('phosphor-globe'),
                MenuItem::make()
                    ->label('Flush Cache')
                    ->icon('phosphor-arrows-clockwise')
                    ->url('/admin/flush-cache')
                    ->color('warning'),
            ])
            ->discoverResources(in: app_path('Filament/Resources'), for: 'App\\Filament\\Resources')
            ->resources(array_filter([
                config('filament-logger.activity_resource'),
            ]))
            ->discoverPages(in: app_path('Filament/Pages'), for: 'App\\Filament\\Pages')
            ->pages([
                Dashboard::class,
            ])
            ->discoverWidgets(in: app_path('Filament/Widgets'), for: 'App\\Filament\\Widgets')
            ->widgets([])
            ->renderHook(
                PanelsRenderHook::TOPBAR_START,
                function (): string {
                    try {
                        return view('filament.widgets.system-status-bar', [
                            'metrics' => app(SystemStatusBar::class)->getMetrics(),
                        ])->render();
                    } catch (Throwable $e) {
                        return '';
                    }
                },
            )
            ->renderHook(
                PanelsRenderHook::HEAD_END,
                fn (): string => '<style>' . file_get_contents(resource_path('css/filament/admin/theme.css')) . '</style>',
            )
            ->navigationGroups(static::buildNavigationGroups())
            ->plugins(static::buildPlugins())
            // Collapsed sidebar becomes a slim icon rail (not fully hidden),
            // shifting page content left so widgets gain horizontal space.
            ->sidebarCollapsibleOnDesktop()
            ->spa()
            ->middleware([
                EncryptCookies::class,
                AddQueuedCookiesToResponse::class,
                StartSession::class,
                AuthenticateSession::class,
                ShareErrorsFromSession::class,
                VerifyCsrfToken::class,
                SubstituteBindings::class,
                DisableBladeIconComponents::class,
                DispatchServingFilamentEvent::class,
            ])
            ->authMiddleware([
                AuthenticateFilament::class,
            ])
            ->authGuard('web');
    }
}