<?php

namespace App\Providers\Filament;

use Leandrocfe\FilamentApexCharts\FilamentApexChartsPlugin;
use BezhanSalleh\FilamentShield\FilamentShieldPlugin;
use Croustibat\FilamentJobsMonitor\FilamentJobsMonitorPlugin;
use Throwable;
use App\Filament\Pages\Dashboard;
use App\Services\SystemStatusBar;
use Filament\Contracts\Plugin;
use App\Http\Middleware\AuthenticateFilament;
use App\Models\Setting;
use Filament\Http\Middleware\DisableBladeIconComponents;
use Filament\Http\Middleware\DispatchServingFilamentEvent;
use Filament\Navigation\MenuItem;
use Filament\Navigation\NavigationGroup;
use Filament\Pages;
use Filament\Panel;
use Filament\PanelProvider;
use Filament\Support\Colors\Color;
use Openplain\FilamentShadcnTheme\Color as ShadcnColor;
use Filament\View\PanelsRenderHook;
use Filament\Widgets;
use Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse;
use Illuminate\Cookie\Middleware\EncryptCookies;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;
use Illuminate\Routing\Middleware\SubstituteBindings;
use Illuminate\Session\Middleware\AuthenticateSession;
use Illuminate\Session\Middleware\StartSession;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\Middleware\ShareErrorsFromSession;
use Filafly\Icons\Phosphor\PhosphorIcons;
use FinityLabs\FinMail\FinMailPlugin;
use Muazzam\SlickScrollbar\SlickScrollbarPlugin;
use Martin6363\SidebarResize\SidebarResizePlugin;

class AdminPanelProvider extends PanelProvider
{
    /**
     * Build the plugin list, gracefully skipping any plugin whose
     * composer package hasn't been installed yet.
     *
     * @return array<int, Plugin>
     */
    protected static function buildPlugins(): array
    {
        $plugins = [];

        // ApexCharts widgets (analytics page)
        if (class_exists(FilamentApexChartsPlugin::class)) {
            $plugins[] = FilamentApexChartsPlugin::make();
        }

        // Granular RBAC (policies generated by `php artisan shield:generate --all`)
        if (class_exists(FilamentShieldPlugin::class)) {
            $plugins[] = FilamentShieldPlugin::make();
        }

        // Queue / failed-job monitor (replaces custom FailedJobs page)
        if (class_exists(FilamentJobsMonitorPlugin::class)) {
            $plugins[] = FilamentJobsMonitorPlugin::make()
                ->navigationCountBadge(false);
        }

        if (class_exists(SlickScrollbarPlugin::class)) {
            $plugins[] = SlickScrollbarPlugin::make()
                ->size('6px')
                ->color('#b8524d')
                ->hoverColor('#c85c56');
        }

        $plugins[] = PhosphorIcons::make()->regular();

        if (class_exists(FinMailPlugin::class)) {
            $plugins[] = FinMailPlugin::make()
                ->navigationGroup('Integrations');
        }

        // Google Analytics widgets (credentials configured via admin panel)
        if (class_exists(\BezhanSalleh\GoogleAnalytics\GoogleAnalyticsPlugin::class)) {
            $plugins[] = \BezhanSalleh\GoogleAnalytics\GoogleAnalyticsPlugin::make();
        }

        // Drag-to-resize navigation sidebar (width persisted in browser localStorage)
        if (class_exists(SidebarResizePlugin::class)) {
            $plugins[] = SidebarResizePlugin::make()
                ->minWidth(220)
                ->maxWidth(460);
        }

        return $plugins;
    }

    protected static function buildNavigationGroups(): array
    {
        $groups = [
            ['key' => 'Overview',         'collapsed' => false, 'icon' => 'phosphor-squares-four'],
            ['key' => 'Content',          'collapsed' => false, 'icon' => 'phosphor-video-camera'],
            ['key' => 'Users & Messages', 'collapsed' => false, 'icon' => 'phosphor-users'],
            ['key' => 'Monetization',     'collapsed' => false, 'icon' => 'phosphor-currency-dollar'],
            ['key' => 'Appearance',       'collapsed' => false, 'icon' => 'phosphor-paint-brush'],
            ['key' => 'Integrations',     'collapsed' => true,  'icon' => 'phosphor-puzzle-piece'],
            ['key' => 'System',           'collapsed' => true,  'icon' => 'phosphor-gear'],
            ['key' => 'Tools',            'collapsed' => true,  'icon' => 'phosphor-wrench'],
        ];

        return array_map(function (array $g) {
            $group = NavigationGroup::make($g['key']);
            if ($g['collapsed']) {
                $group->collapsed();
            }
            if (!empty($g['icon'])) {
                $group->icon($g['icon']);
            }
            return $group;
        }, $groups);
    }

    /**
     * Muted brand red used as the panel primary (links, active states,
     * highlights). Lower chroma than shadcn's Red so it reads comfortably
     * on the dark zinc backdrop while staying clearly red.
     *
     * Follows the shadcn "doubled shades" structure (50=500, 100=600,
     * 200=700) so the theme's dark-mode shade-swap is a no-op and the
     * colour never flips to near-white.
     *
     * @return array<int, string>
     */
    protected static function mutedRed(): array
    {
        return [
            50  => 'oklch(0.62 0.14 25)',
            100 => 'oklch(0.565 0.14 26)',
            200 => 'oklch(0.5 0.13 27)',
            300 => 'oklch(0.79 0.07 22)',
            400 => 'oklch(0.7 0.11 24)',
            500 => 'oklch(0.62 0.14 25)',
            600 => 'oklch(0.565 0.14 26)',
            700 => 'oklch(0.5 0.13 27)',
            800 => 'oklch(0.44 0.11 27)',
            900 => 'oklch(0.39 0.095 26)',
            950 => 'oklch(0.98 0 0)',
        ];
    }

    /**
     * Bright "firetruck" red reserved for destructive/danger actions.
     * Higher chroma than the muted primary so destructive buttons stand
     * out from the everyday accent. (~#ee1c25)
     *
     * @return array<int, string>
     */
    protected static function firetruckRed(): array
    {
        return [
            50  => 'oklch(0.6 0.245 27)',
            100 => 'oklch(0.55 0.245 28)',
            200 => 'oklch(0.49 0.215 28)',
            300 => 'oklch(0.8 0.12 22)',
            400 => 'oklch(0.7 0.2 25)',
            500 => 'oklch(0.6 0.245 27)',
            600 => 'oklch(0.55 0.245 28)',
            700 => 'oklch(0.49 0.215 28)',
            800 => 'oklch(0.43 0.18 28)',
            900 => 'oklch(0.38 0.145 27)',
            950 => 'oklch(0.98 0 0)',
        ];
    }

    public function panel(Panel $panel): Panel
    {
        // Resolve site logo for admin panel branding
        $brandLogo = null;
        $brandName = 'HubTube';
        try {
            $siteLogo = Setting::get('site_logo', '');
            if ($siteLogo) {
                // Use same URL resolution as frontend: /storage/ prefix for relative paths
                if (str_starts_with($siteLogo, 'http://') || str_starts_with($siteLogo, 'https://') || str_starts_with($siteLogo, '/')) {
                    $brandLogo = $siteLogo;
                } else {
                    $brandLogo = '/storage/' . $siteLogo;
                }
            }
            $brandName = Setting::get('site_title', 'HubTube') ?: 'HubTube';
        } catch (Throwable $e) {
            // Database may not be available during boot
        }

        // Resolve favicon for admin panel
        $faviconUrl = null;
        try {
            $siteFavicon = Setting::get('site_favicon', '');
            if ($siteFavicon) {
                if (str_starts_with($siteFavicon, 'http://') || str_starts_with($siteFavicon, 'https://') || str_starts_with($siteFavicon, '/')) {
                    $faviconUrl = $siteFavicon;
                } else {
                    $faviconUrl = '/storage/' . $siteFavicon;
                }
            }
        } catch (Throwable $e) {
            // Database may not be available during boot
        }

        $builder = $panel
            ->default()
            ->id('admin')
            ->path('admin')
            ->darkMode(true, true)
            ->brandName($brandName)
            ->font('Inter')
            ->colors([
                'primary' => static::mutedRed(),
                'danger'  => static::firetruckRed(),
                'warning' => ShadcnColor::Yellow,
                'success' => ShadcnColor::Green,
                'info'    => ShadcnColor::Blue,
                'gray'    => ShadcnColor::Default,
            ]);

        if ($faviconUrl) {
            $builder = $builder->favicon($faviconUrl);
        }

        if ($brandLogo) {
            $builder = $builder
                ->brandLogo($brandLogo)
                ->brandLogoHeight('2rem');
        }

        return $builder
            ->login()
            ->profile()
            ->userMenuItems([
                MenuItem::make()
                    ->label('View Site')
                    ->url('/')
                    ->icon('phosphor-globe'),
                MenuItem::make()
                    ->label('Flush Cache')
                    ->icon('phosphor-arrows-clockwise')
                    ->url('/admin/flush-cache')
                    ->color('warning'),
            ])
            ->discoverResources(in: app_path('Filament/Resources'), for: 'App\\Filament\\Resources')
            ->resources(array_filter([
                config('filament-logger.activity_resource'),
            ]))
            ->discoverPages(in: app_path('Filament/Pages'), for: 'App\\Filament\\Pages')
            ->pages([
                Dashboard::class,
            ])
            ->discoverWidgets(in: app_path('Filament/Widgets'), for: 'App\\Filament\\Widgets')
            ->widgets([])
            ->renderHook(
                PanelsRenderHook::TOPBAR_END,
                function (): string {
                    try {
                        return view('filament.widgets.system-status-bar', [
                            'items' => app(SystemStatusBar::class)->getActionItems(),
                        ])->render();
                    } catch (Throwable $e) {
                        return '';
                    }
                },
            )
            ->renderHook(
                PanelsRenderHook::HEAD_END,
                fn (): string => '<style>' . file_get_contents(resource_path('css/filament/admin/theme.css')) . '</style>',
            )
            ->renderHook(
                PanelsRenderHook::BODY_END,
                fn (): string => view('filament.partials.session-expired-overlay')->render(),
            )
            ->navigationGroups(static::buildNavigationGroups())
            ->plugins(static::buildPlugins())
            // Collapsed sidebar becomes a slim icon rail (not fully hidden),
            // shifting page content left so widgets gain horizontal space.
            ->sidebarCollapsibleOnDesktop()
            ->spa()
            ->middleware([
                EncryptCookies::class,
                AddQueuedCookiesToResponse::class,
                StartSession::class,
                AuthenticateSession::class,
                ShareErrorsFromSession::class,
                VerifyCsrfToken::class,
                SubstituteBindings::class,
                DisableBladeIconComponents::class,
                DispatchServingFilamentEvent::class,
            ])
            ->authMiddleware([
                AuthenticateFilament::class,
            ])
            ->authGuard('web');
    }
}