<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Drop columns/tables/settings for removed features:
     *  - Shorts (is_short column on videos)
     *  - Gifts (gifts table + wallet gift_* transaction rows + payment settings + streaming settings)
     *  - Leftover live-streaming settings
     */
    public function up(): void
    {
        // --- Shorts ---
        if (Schema::hasTable('videos') && Schema::hasColumn('videos', 'is_short')) {
            Schema::table('videos', function (Blueprint $table) {
                // Drop index if it exists (name auto-generated by Laravel)
                try {
                    $table->dropIndex(['is_short']);
                } catch (\Throwable $e) {
                    // index may not exist on older schemas
                }
                $table->dropColumn('is_short');
            });
        }

        // --- Gifts ---
        Schema::dropIfExists('gifts');

        // Remove gift-type wallet transactions (history is preserved by type rename → 'other')
        if (Schema::hasTable('wallet_transactions')) {
            DB::table('wallet_transactions')
                ->whereIn('type', ['gift_sent', 'gift_received'])
                ->delete();
        }

        // Remove gift-type notifications
        if (Schema::hasTable('notifications')) {
            DB::table('notifications')
                ->whereIn('type', ['gift_received', 'live_started'])
                ->delete();
        }

        // --- Settings cleanup (gifts, live, shorts, agora) ---
        if (Schema::hasTable('settings')) {
            DB::table('settings')->whereIn('key', [
                'gift_platform_cut',
                'gifts_enabled',
                'live_streaming_enabled',
                'max_stream_duration',
                'require_verification_to_stream',
                'agora_token_expiry',
                'agora_app_id',
                'agora_app_certificate',
                'free_users_can_go_live',
                'nav_live_icon',
                'nav_live_color',
                'nav_shorts_icon',
                'nav_shorts_color',
                // Light-theme settings (dark-only lockdown)
                'theme_mode',
                'allow_user_theme_toggle',
                'light_bg_primary',
                'light_bg_secondary',
                'light_bg_card',
                'light_accent_color',
                'light_text_primary',
                'light_text_secondary',
                'light_border_color',
            ])->delete();
        }
    }

    /**
     * No-down: this migration removes deprecated features permanently.
     */
    public function down(): void
    {
        // intentionally left blank — removed features are not restorable
    }
};
