#!/usr/bin/env bash
#
# Maddy Mail Server Setup Script for HubTube
# -------------------------------------------
# This script installs and configures Maddy as a local SMTP server
# for sending transactional emails (signup verification, payment receipts,
# subscription notifications, withdrawal confirmations, etc.)
#
# Requirements:
#   - Ubuntu 20.04+ / Debian 11+ (amd64)
#   - Root or sudo access
#   - A domain name with DNS access (for DKIM/SPF/DMARC)
#
# Usage:
#   sudo bash setup-maddy.sh yourdomain.com [mail.yourdomain.com]
#
# Arguments:
#   $1 - Primary domain (e.g., yourdomain.com)
#   $2 - Mail hostname (optional, defaults to mail.$1)
#

set -euo pipefail

# ── Colors ──
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; }
info() { echo -e "${CYAN}[i]${NC} $1"; }

# ── Validate arguments ──
if [ $# -lt 1 ]; then
    err "Usage: sudo bash setup-maddy.sh <domain> [mail-hostname]"
    err "  Example: sudo bash setup-maddy.sh example.com"
    err "  Example: sudo bash setup-maddy.sh example.com mail.example.com"
    exit 1
fi

if [ "$EUID" -ne 0 ]; then
    err "This script must be run as root (use sudo)."
    exit 1
fi

DOMAIN="$1"
MAIL_HOST="${2:-mail.$DOMAIN}"
MADDY_VERSION="0.7.1"
MADDY_URL="https://github.com/foxcpp/maddy/releases/download/v${MADDY_VERSION}/maddy-${MADDY_VERSION}-x86_64-linux-musl.tar.zst"
MADDY_FALLBACK_URL="https://github.com/foxcpp/maddy/releases/download/v${MADDY_VERSION}/maddy-${MADDY_VERSION}-x86_64-linux-musl.tar.gz"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Maddy Mail Server Setup for HubTube"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
info "Domain:        $DOMAIN"
info "Mail hostname: $MAIL_HOST"
echo ""

# ── Step 1: Install dependencies ──
log "Installing dependencies..."
apt-get update -qq
apt-get install -y -qq wget tar zstd certbot > /dev/null 2>&1

# ── Step 2: Create maddy user ──
if ! id -u maddy &>/dev/null; then
    log "Creating maddy system user..."
    useradd -r -s /usr/sbin/nologin -d /var/lib/maddy maddy
else
    log "Maddy user already exists."
fi

# ── Step 3: Download and install Maddy ──
if command -v maddy &>/dev/null; then
    INSTALLED_VER=$(maddy version 2>/dev/null | head -1 || echo "unknown")
    warn "Maddy already installed: $INSTALLED_VER"
    warn "Reinstalling to version $MADDY_VERSION..."
fi

log "Downloading Maddy v${MADDY_VERSION}..."
cd /tmp

# Try zstd first, fall back to gzip
if wget -q "$MADDY_URL" -O maddy.tar.zst 2>/dev/null; then
    tar --use-compress-program=unzstd -xf maddy.tar.zst
elif wget -q "$MADDY_FALLBACK_URL" -O maddy.tar.gz 2>/dev/null; then
    tar -xzf maddy.tar.gz
else
    err "Failed to download Maddy. Check https://github.com/foxcpp/maddy/releases"
    exit 1
fi

# Install binaries
cp -f maddy-*/maddy /usr/local/bin/maddy
cp -f maddy-*/maddyctl /usr/local/bin/maddyctl
chmod +x /usr/local/bin/maddy /usr/local/bin/maddyctl
rm -rf /tmp/maddy* 

log "Maddy installed to /usr/local/bin/maddy"

# ── Step 4: Create directories ──
mkdir -p /etc/maddy
mkdir -p /var/lib/maddy
mkdir -p /var/log/maddy
mkdir -p /run/maddy
chown -R maddy:maddy /var/lib/maddy /var/log/maddy /run/maddy

# ── Step 5: Obtain TLS certificate ──
log "Obtaining TLS certificate for $MAIL_HOST..."
if [ -d "/etc/letsencrypt/live/$MAIL_HOST" ]; then
    warn "Certificate already exists for $MAIL_HOST, skipping."
else
    info "Make sure port 80 is open and $MAIL_HOST points to this server."
    info "If certbot fails, you can run it manually later:"
    info "  certbot certonly --standalone -d $MAIL_HOST"
    echo ""
    
    certbot certonly --standalone -d "$MAIL_HOST" --non-interactive --agree-tos --register-unsafely-without-email || {
        warn "Certbot failed. You'll need to obtain a TLS certificate manually."
        warn "Run: certbot certonly --standalone -d $MAIL_HOST"
        warn "Then update /etc/maddy/maddy.conf with the certificate paths."
    }
fi

# ── Step 6: Generate configuration ──
log "Writing /etc/maddy/maddy.conf..."
cat > /etc/maddy/maddy.conf << MADDYCONF
# Maddy Mail Server Configuration for HubTube
# Generated by setup-maddy.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

$(hostname) = $MAIL_HOST
primary_domain = $DOMAIN

# TLS certificates (Let's Encrypt)
tls file /etc/letsencrypt/live/$MAIL_HOST/fullchain.pem /etc/letsencrypt/live/$MAIL_HOST/privkey.pem

# Logging
log syslog

# ── Local storage ──
storage.imapsql local_mailboxes {
    driver sqlite3
    dsn /var/lib/maddy/imapsql.db
}

# ── Authentication ──
auth.pass_table local_authdb {
    table sql_table {
        driver sqlite3
        dsn /var/lib/maddy/credentials.db
        table_name passwords
    }
}

# ── Outbound delivery (sending emails) ──
target.remote outbound_delivery {
    limits {
        all rate 20 1s    # Max 20 emails/second globally
        destination rate 5 1s  # Max 5/sec per destination domain
    }

    mx_auth {
        dane
        mtasts {
            cache fs
            fs_dir /var/lib/maddy/mtasts_cache
        }
        local_policy {
            min_tls_level encrypted
            min_mx_level none
        }
    }
}

# ── DKIM signing ──
modify.dkim local_dkim {
    debug no
    domains {primary_domain}
    selector hubtube
    key_path /var/lib/maddy/dkim_keys/{domain}_{selector}.dns_key
    header_canon relaxed
    body_canon relaxed
    sig_expiry 120h  # 5 days
    require_sender_match envelope
    allow_body_subset yes
}

# ── Submission (port 587 — Laravel connects here) ──
smtp tcp://0.0.0.0:587 {
    debug no
    io_debug no

    # Require TLS for authentication
    starttls

    # Require authentication
    auth &local_authdb

    source {primary_domain} {
        check {
            authorize_sender {
                prepare_email &local_authdb
                auth_normalize auto
            }
        }

        modify {
            replace_addr &local_authdb
            use &local_dkim
        }

        deliver_to &outbound_delivery
    }

    default_source {
        reject 501 5.1.8 "Sender domain not allowed"
    }
}

# ── MX (port 25 — receiving bounce notifications) ──
smtp tcp://0.0.0.0:25 {
    debug no
    io_debug no

    source {
        default_destination {
            reject 550 5.1.1 "This server does not accept incoming mail"
        }
    }

    destination {primary_domain} {
        deliver_to &local_mailboxes
    }

    default_destination {
        reject 550 5.1.1 "User not found"
    }
}
MADDYCONF

log "Configuration written."

# ── Step 7: Generate DKIM keys ──
log "Generating DKIM keys..."
mkdir -p /var/lib/maddy/dkim_keys
if [ ! -f "/var/lib/maddy/dkim_keys/${DOMAIN}_hubtube.dns_key" ]; then
    # maddy will auto-generate keys on first run, but we can trigger it
    # by starting briefly or using openssl
    openssl genrsa -out "/var/lib/maddy/dkim_keys/${DOMAIN}_hubtube.key" 2048 2>/dev/null
    openssl rsa -in "/var/lib/maddy/dkim_keys/${DOMAIN}_hubtube.key" \
        -pubout -out "/var/lib/maddy/dkim_keys/${DOMAIN}_hubtube.dns_key" 2>/dev/null
    chown -R maddy:maddy /var/lib/maddy/dkim_keys
    log "DKIM keys generated."
else
    warn "DKIM keys already exist, skipping."
fi

# Extract the public key for DNS
DKIM_PUBKEY=$(grep -v "PUBLIC KEY" "/var/lib/maddy/dkim_keys/${DOMAIN}_hubtube.dns_key" | tr -d '\n')

# ── Step 8: Create systemd service ──
log "Creating systemd service..."
cat > /etc/systemd/system/maddy.service << 'SYSTEMD'
[Unit]
Description=Maddy Mail Server
Documentation=man:maddy(1)
Documentation=man:maddy.conf(5)
Documentation=https://maddy.email
After=network.target

[Service]
Type=notify
NotifyAccess=main
User=maddy
Group=maddy

# Capabilities for binding to privileged ports (25, 587)
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE

ExecStart=/usr/local/bin/maddy -config /etc/maddy/maddy.conf
ExecReload=/bin/kill -USR1 $MAINPID

Restart=on-failure
RestartSec=5s

# Security hardening
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/maddy /var/log/maddy /run/maddy
PrivateTmp=true
NoNewPrivileges=true

# Allow reading TLS certs
ReadOnlyPaths=/etc/letsencrypt

[Install]
WantedBy=multi-user.target
SYSTEMD

systemctl daemon-reload

# ── Step 9: Create HubTube mail account ──
log "Creating HubTube mail account..."
MAIL_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)

# Create the account using maddyctl
maddyctl --config /etc/maddy/maddy.conf creds create "noreply@${DOMAIN}" <<< "$MAIL_PASSWORD
$MAIL_PASSWORD" 2>/dev/null || {
    warn "Could not create credentials now (Maddy may need to run first)."
    warn "After starting Maddy, run:"
    warn "  maddyctl creds create noreply@${DOMAIN}"
}

# ── Step 10: Start Maddy ──
log "Starting Maddy..."
systemctl enable maddy
systemctl start maddy || {
    warn "Maddy failed to start. Check: journalctl -u maddy -n 50"
    warn "Common issues: port 25/587 already in use, TLS cert missing."
}

# ── Step 11: Save credentials ──
CREDS_FILE="/etc/maddy/.hubtube-credentials"
cat > "$CREDS_FILE" << CREDS
# HubTube Mail Credentials
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# ⚠️  Keep this file secure — delete after configuring HubTube

MAIL_MAILER=smtp
MAIL_HOST=127.0.0.1
MAIL_PORT=587
MAIL_USERNAME=noreply@${DOMAIN}
MAIL_PASSWORD=${MAIL_PASSWORD}
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=noreply@${DOMAIN}
MAIL_FROM_NAME="\${APP_NAME}"
CREDS
chmod 600 "$CREDS_FILE"

# ── Done! Print summary ──
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ Maddy Mail Server Installed!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${CYAN}Laravel .env settings:${NC}"
echo "  MAIL_MAILER=smtp"
echo "  MAIL_HOST=127.0.0.1"
echo "  MAIL_PORT=587"
echo "  MAIL_USERNAME=noreply@${DOMAIN}"
echo "  MAIL_PASSWORD=${MAIL_PASSWORD}"
echo "  MAIL_ENCRYPTION=tls"
echo "  MAIL_FROM_ADDRESS=noreply@${DOMAIN}"
echo ""
echo -e "${CYAN}Credentials saved to:${NC} $CREDS_FILE"
echo ""
echo -e "${YELLOW}━━━ REQUIRED DNS RECORDS ━━━${NC}"
echo ""
echo -e "${CYAN}1. MX Record:${NC}"
echo "   ${DOMAIN}  MX  10  ${MAIL_HOST}"
echo ""
echo -e "${CYAN}2. SPF Record (TXT):${NC}"
echo "   ${DOMAIN}  TXT  \"v=spf1 mx a:${MAIL_HOST} ~all\""
echo ""
echo -e "${CYAN}3. DKIM Record (TXT):${NC}"
echo "   hubtube._domainkey.${DOMAIN}  TXT  \"v=DKIM1; k=rsa; p=${DKIM_PUBKEY}\""
echo ""
echo -e "${CYAN}4. DMARC Record (TXT):${NC}"
echo "   _dmarc.${DOMAIN}  TXT  \"v=DMARC1; p=quarantine; rua=mailto:postmaster@${DOMAIN}; pct=100\""
echo ""
echo -e "${CYAN}5. Reverse DNS (PTR):${NC}"
echo "   Set your server IP's PTR record to: ${MAIL_HOST}"
echo "   (Configure this in your hosting provider's control panel)"
echo ""
echo -e "${YELLOW}━━━ USEFUL COMMANDS ━━━${NC}"
echo ""
echo "  systemctl status maddy        # Check status"
echo "  journalctl -u maddy -f        # View logs"
echo "  systemctl restart maddy       # Restart"
echo "  maddyctl creds list           # List accounts"
echo "  maddyctl creds create <user>  # Add account"
echo ""
echo -e "${YELLOW}━━━ DELIVERABILITY TIPS ━━━${NC}"
echo ""
echo "  1. Add ALL DNS records above before sending emails"
echo "  2. Warm up slowly: send 50-100 emails/day for the first week"
echo "  3. Monitor bounces: journalctl -u maddy | grep -i bounce"
echo "  4. Test your setup: https://www.mail-tester.com"
echo "  5. Check blacklists: https://mxtoolbox.com/blacklists.aspx"
echo ""
